### ISSUE TITLE
Can RubbleDB run without replications?

### ISSUE THREAD

**Issue by CS0522** [lei-houjyu/RubbleDB#2]
Hi, I'm wondering whether RubbleDB could run without replications, which means only 2 nodes, node-0 as the client, and node-1 as the primary node? I noticed from the code that RubbleDB may need setup both `primary_node` and `tail_node`.

Thanks for your help!

**Comment by lei-houjyu** [comment]
Hi, thanks for asking. Unfortunately, RubbleDB is designed to run with replication, i.e., there should be at least one secondary node. This is because the purpose of RubbleDB is to avoid redundant compaction jobs between replicas, if there is no replication at all, RubbleDB won't make any improvements over vanilla RocksDB.

**Comment by CS0522** [comment]
I got it, thanks for help!
